development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Quotes on Rails
  admin_email: scott@scott-olson.org
  
test:
  <<: *non_production_settings

staging:
  site_url: http://quotes.scott-olson.org
  site_name: Quotes on Rails
  admin_email: scott@scott-olson.org
  
production:
  site_url: http://www.example.com
  site_name: Quotes on Rails
  admin_email: scott@scott-olson.org
